# Generated by Django 6.0 on 2025-12-15 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(choices=[(datetime.time(8, 0), '08:00'), (datetime.time(8, 10), '08:10'), (datetime.time(8, 20), '08:20'), (datetime.time(8, 30), '08:30'), (datetime.time(8, 40), '08:40'), (datetime.time(8, 50), '08:50'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 10), '09:10'), (datetime.time(9, 20), '09:20'), (datetime.time(9, 30), '09:30'), (datetime.time(9, 40), '09:40'), (datetime.time(9, 50), '09:50'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 10), '10:10'), (datetime.time(10, 20), '10:20'), (datetime.time(10, 30), '10:30'), (datetime.time(10, 40), '10:40'), (datetime.time(10, 50), '10:50'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 10), '11:10'), (datetime.time(11, 20), '11:20'), (datetime.time(11, 30), '11:30'), (datetime.time(11, 40), '11:40'), (datetime.time(11, 50), '11:50'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 10), '12:10'), (datetime.time(12, 20), '12:20'), (datetime.time(12, 30), '12:30'), (datetime.time(12, 40), '12:40'), (datetime.time(12, 50), '12:50'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 10), '13:10'), (datetime.time(13, 20), '13:20'), (datetime.time(13, 30), '13:30'), (datetime.time(13, 40), '13:40'), (datetime.time(13, 50), '13:50'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 10), '14:10'), (datetime.time(14, 20), '14:20'), (datetime.time(14, 30), '14:30'), (datetime.time(14, 40), '14:40'), (datetime.time(14, 50), '14:50'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 10), '15:10'), (datetime.time(15, 20), '15:20'), (datetime.time(15, 30), '15:30'), (datetime.time(15, 40), '15:40'), (datetime.time(15, 50), '15:50'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 10), '16:10'), (datetime.time(16, 20), '16:20'), (datetime.time(16, 30), '16:30'), (datetime.time(16, 40), '16:40'), (datetime.time(16, 50), '16:50')]),
        ),
    ]
